<a href="https://colab.research.google.com/github/AlinaMidhath/PYTHON-DA-ML/blob/main/alina_day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DA**



NUMPY LIBRARY

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

**ARRAY CREATION**
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [ ]:
import numpy as np
my_arr = np.array([1,2, 3, 4, 5])#using lists to create arrays
array1 = np.array(["hi" , "hello" , "wassup"])
array2 = np.array([2.2, 3.4, 4.5, 5.6])
array3 = np.array(['a', 'b', 'c', 'd'])
print(my_arr)
print(my_arr.dtype)
print(array1.dtype)# returns unsigned int value
print(array2.dtype)
print(array3.dtype)

[1 2 3 4 5]
int64
<U6
float64
<U1


**ACCESSING ARRAY ELEMENTS**

In [ ]:
array4 = np.array([1,2,3,4,5,6,7,8,9])
print(array4[4]) #accessing
print(array4[0])
print(array4[-1])
print(array4[4] + array4[5])

5
1
9
11


**SLICING**

In [ ]:
array5 = array4[::2] #array4[0::2]
print(array5)

[1 3 5 7 9]


In [ ]:
print(array5[::-1])

[9 7 5 3 1]


2D

In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr1[0])
print(arr1[1])
print(arr1.shape)#The shape of an array is the number of elements in each dimension.
print(arr1[1][2])
print(arr1[0][1:3])

[1 2 3 4]
[5 6 7 8]
(2, 4)
7
[2 3]


A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9,10,11,12], ndmin=5)# its becoming a 5d array
print(arr2)
print("shape of array: ", arr2.shape) #it will show 5 dimensions(like (x,y) have 2 dimensions this will have (x,y,z,a,b))

[[[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]]]
shape of array:  (1, 1, 1, 1, 12)


Convert the following 1-D array with 12 elements into a 2-D array.
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr2.reshape(4,3) #reshapes/changes the dimensions

print(newarr)
print(newarr.shape) #gives the dimension

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr2 = arr2.reshape(2,3,2) #(row,dimension,column) also row*dim*col shd be = to no. of elements
print(newarr2)
print(newarr2.shape)
print(newarr2.ndim)#Tells the dimensions of the array

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [ ]:
newarr3 = arr2.reshape(3,2,2)
print(newarr3)
print(newarr3.shape)
print(newarr3.ndim)#Tells the dimensions of the array

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
3


**Flattening** - converting any array to one dimensional array

In [ ]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])#2d array creation
print(arr1)
arr4=arr1.reshape(-1)
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])
print(arr5)
arr6= arr5.reshape(-1)
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr2 =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr3 = arr2.reshape(3,2,2)
print(newarr3)
print(newarr3.shape)
print(newarr3.ndim)
arr7= newarr3.reshape(-1)
print(arr7)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


loops

In [ ]:
ar1 = np.array([[1,2,3],[4,5,6]])
for element in ar1: # 2 for loops because it is a 2d arrar
  for ele in element:
    print(ele)

1
2
3
4
5
6


In [ ]:
ar2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for element in ar2: # 3 for loops because it is a 3d array
  for ele in element:
    for e in ele:
      print(e)


1
2
3
4
5
6
7
8
9
10
11
12


**JOINING**

In [ ]:
ar3 = np.array([1,2,3,4,5,6,7,8])
ar4 = np.array([2,3,4,5])
ar = np.concatenate((ar3,ar4))
print(ar)

[1 2 3 4 5 6 7 8 2 3 4 5]


**SPLIT**

In [ ]:
ar5 = np.array([1,2,3,4,5,6,7,8,9,10])
ar6 = np.array_split(ar5,3)
print(ar6)
print(ar6[2])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[ 8  9 10]


**SORT**

In [ ]:
ar7 = np.array([-9,10,2,-4])
print(np.sort(ar7))

[-9 -4  2 10]


In [ ]:
ar8 = np.array([False,True,True,False])
print(np.sort(ar8))

[False False  True  True]


In [ ]:
ar9 = np.array(['e','a','u','o','i'])
print(np.sort(ar9))

['a' 'e' 'i' 'o' 'u']


In [ ]:
ar10 = np.array(["midhath","basma", "sarah"])
print(np.sort(ar10))

['basma' 'midhath' 'sarah']


In [ ]:
ar11 = np.array([1,2,3,4,5,6,7,8,9,10])
filter_array =[]
for ele in ar11:
  if ele%2 ==0:
    filter_array.append(True)
  else:
    filter_array.append(False)

print(filter_array)

[False, True, False, True, False, True, False, True, False, True]


priinting even and odd numbers in an array

In [ ]:
ar11 = np.array([1,2,3,4,5,6,7,8,9,10])
even = []
odd = []
for ele in ar11:
  if ele%2 ==0:
    even.append(ele)
  else:
    odd.append(ele)

print(even)
print(odd)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]
